//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormDenemeEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class formdenemeEntities : DbContext
    {
        public formdenemeEntities()
            : base("name=formdenemeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    
        public virtual int PersonelInsert(string adSoyad, string sehir, string alan)
        {
            var adSoyadParameter = adSoyad != null ?
                new ObjectParameter("AdSoyad", adSoyad) :
                new ObjectParameter("AdSoyad", typeof(string));
    
            var sehirParameter = sehir != null ?
                new ObjectParameter("Sehir", sehir) :
                new ObjectParameter("Sehir", typeof(string));
    
            var alanParameter = alan != null ?
                new ObjectParameter("Alan", alan) :
                new ObjectParameter("Alan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PersonelInsert", adSoyadParameter, sehirParameter, alanParameter);
        }
    
        public virtual int UpdatePersonel(Nullable<int> personelId, string adSoyad, string sehir, string alan)
        {
            var personelIdParameter = personelId.HasValue ?
                new ObjectParameter("PersonelId", personelId) :
                new ObjectParameter("PersonelId", typeof(int));
    
            var adSoyadParameter = adSoyad != null ?
                new ObjectParameter("AdSoyad", adSoyad) :
                new ObjectParameter("AdSoyad", typeof(string));
    
            var sehirParameter = sehir != null ?
                new ObjectParameter("Sehir", sehir) :
                new ObjectParameter("Sehir", typeof(string));
    
            var alanParameter = alan != null ?
                new ObjectParameter("Alan", alan) :
                new ObjectParameter("Alan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePersonel", personelIdParameter, adSoyadParameter, sehirParameter, alanParameter);
        }
    }
}
